project:
  type: website
  output-dir: docs
website:
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-41NGYQ2T3X"
    anonymize-ip: true

  navbar:
    background: "transparent"
    foreground: "black"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: pt/index.qmd  # Lien vers la page principale Portfolio
      - text: "Shiny App"
        href: shiny/index.qmd
      - text: "Contact"
        href: contact/index.qmd

  page-footer: 
    background: "transparent"
    foreground: "black"
    left: "Copyright 2024" 
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/yoann-pull/
      - icon: github 
        href: https://github.com/YoannPull
      - icon: envelope
        href: mailto:yoann.pull.pro@gmail.com    

format:
  html:
    #theme: mint
    css: styles.css
    toc: false
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html
